export const plantsData = [
  {
    name: "Spider Plant",
    type: "Chlorophytum",
    light: "Perennial",
    watering: "Medium",
    blooming: "Rare",
    features: "Air-purifying, Easy to care",
  },
  {
    name: "Aloe Vera",
    type: "Aloe",
    light: "Bright light",
    watering: "Low",
    blooming: "Occasional",
    features: "Medicinal, Air-purifying",
  },
  {
    name: "Peace Lily",
    type: "Spathiphyllum",
    light: "Shade",
    watering: "Medium",
    blooming: "Frequent",
    features: "Air-purifying, Easy to care",
  },
  {
    name: "Snake Plant",
    type: "Sansevieria",
    light: "Low light",
    watering: "Low",
    blooming: "Rare",
    features: "Air-purifying, Low maintenance",
  },
  {
    name: "Boston Fern",
    type: "Nephrolepis exaltata",
    light: "Indirect sunlight",
    watering: "High",
    blooming: "Never",
    features: "Air-purifying, Moisture loving",
  },
];
